language: node_js

node_js:
  - '10'

branches:
  only:
  - master
  - develop

install:
  - npm install

cache:
  directories:
    - node_modules

matrix:
  include:
    - before_script:
        echo "Running powerfield-app"
      script:
        - npm run lint --project powerfield-app
        - ng build --prod --base-href https://youritornier.github.io/powerfield/ --project powerfield-app
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/powerfield-app
        on:
          branch: master
    - before_script:
        echo "Running powerfield"
      script:
        - npm run lint --project powerfield
        - npm run test-ci
        - ng build --project powerfield
      before_deploy:
        cd projects/powerfield
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master
