language: node_js

node_js:
  - '10'

branches:
  only:
  - master
  - /release\/.*/
  - develop

install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test-ci  
  - npm run build --prod
